{"uuid": "2948251a-743b-4023-9409-c48bce93b158", "children": ["94fa2866-f10c-4ee7-b4c4-3640de203476"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Failed to start browser C:\\Users\\karim.belboukhari\\.cache\\selenium\\firefox\\win64\\129.0.2\\firefox.exe: IO Error: Ce programme est bloqué par une stratégie de groupe. Pour plus d’informations, contactez votre administrateur système. (os error 1260)\n\n", "trace": "  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\testCases\\conftest.py\", line 15, in setup\n    driver = webdriver.Firefox()\n             ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 71, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\karim.belboukhari\\HRMTestFramework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725143934375, "stop": 1725143940283}], "start": 1725143934375, "stop": 1725143940312}